# Generated by Django 4.2.7 on 2023-11-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter book's genre, like science,fiction,non-fiction", max_length=128, verbose_name="Book's Genre")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="books' title", max_length=200, verbose_name='book title')),
                ('author', models.CharField(max_length=128)),
                ('summary', models.TextField(help_text='the summary of the book', max_length=1000)),
                ('isbn', models.CharField(help_text="the book's ISBN, <a href='https://www.isbn-international.org/content/what-is-isbn'>what is ISBN</a>", max_length=13, verbose_name='ISBN')),
                ('published_at', models.DateField()),
                ('genre', models.ManyToManyField(help_text='book genre', to='bookstore.genre')),
            ],
        ),
    ]
