# Generated by Django 4.2.7 on 2023-11-15 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 15, 22, 7, 35, 554944)),
        ),
    ]
