# Generated by Django 4.2.7 on 2023-11-15 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 15, 22, 8, 34, 174276, tzinfo=datetime.timezone.utc)),
        ),
    ]
