# Generated by Django 4.2.7 on 2023-11-16 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_alter_book_author_alter_book_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 16, 3, 35, 4, 99754, tzinfo=datetime.timezone.utc)),
        ),
    ]
